# Example config file
# The parameters are stored following the format :
# param_name type value

# NECESSARY PARAMETERS
# For the core_state
# Max SH degree for the core flow coefficients
Lu int 18
# Max SH degree for the magnetic field coefficients
Lb int 13
# Max SH degree for the secular variation and subgrid-errors coefficients
Lsv int 13

# Starting analysis date
t_start_analysis float 1998
# Finish analysis date
t_end_analysis float 2023
# Timestep of forecasts (6 months)
dt_f float 0.5
# dt_a / dt_f ratio (analysis every 2 forecasts = 1 year)
dt_a_f_ratio int 1
#Start forecast 10 dta before t_start_analysis (so 1960-10 = 1950)
N_dta_start_forecast int 10
#End forecast 10 dta after t_end_analysis (so 1965+10 = 1975)
N_dta_end_forecast int 10

# OPTIONAL PARAMETERS
# Number of angles for Legendre polynomials evaluation
Nth_legendre int 64
# Time constant for diagonal AR-1 process of U
TauU years 30
# Time constant for diagonal AR-1 process of ER
TauE years 10
# Directory where to find the prior data (relative to the config path)
prior_dir str data/priors/50path
# Type of the prior data ('0path', '50path', '71path' and '100path')
prior_type str 50path
# Blackman smoothing window duration (only used if AR3 process)
dt_smoothing float 3.2
# Subsampling of the prior (only used if AR1 process)
dt_sampling float 5
# Directory where to find the observation data (relative to the config path)
obs_dir str data/observations/CHAOS-7
# Type of observation to consider ('COVOBS', 'COVOBS_hdf5', 'chaos_hdf5' and 'GO_VO' are supported)
obs_type str chaos_hdf5
# Type of the AR process ('diag' (AR1), (dense) 'AR1', (dense) 'AR3')
AR_type str diag
# Number of coefficients for the PCA of U
# If 0 or negative, no PCA will be done (default)
N_pca_u int 100
# Normalisation to use for U on which the PCA is performed ('energy' or 'None' (default))
pca_norm str energy
# Type of initialihttps://filesender.renater.fr/?s=download&token=fa5a64ae-d6d2-42a8-8a63-41da20fbe469sation for the core_state ('normal' or 'from_file')
core_state_init str normal
# 'normal' performs a normal draw around it for each realisation (default)

# parameters that control the output hdf5 file
# Controls whether to output (1) or not (0) the analysis state
out_analysis int 1
# Controls whether to output (1) or not (0) the forecast state
out_forecast int 1
# Controls whether to output (1) or not (0) the computed state
out_computed int 1
# Controls whether to output (1) or not (0) the misfit state
out_misfits int 1

# reduce noise coming from empirical covariance computation
# advised value is 35/Nb_realisations for AR1 
# would be good for 100 realisations and AR1
#remove_spurious float 0.35 

# controls if we consider U and ER independant (1) or not (0) in the AR process (forecast)
combined_U_ER_forecast int 0
#set GOVO SWARM error matrix to dense else diag (FOR SWARM 4M ONLY)
SW_err str dense